### ISSUE TITLE
Reply count is off by one

### ISSUE THREAD

**Issue by jackwickham** [InvisionPowerServices/Mobile-App-Issues#39]
## Platform

- Android

## Problem
In the list of topics, when it says "x replies" it actually means "x posts" or "x-1 replies". On the websites it is displayed as "x-1 replies".

## Steps to reproduce

1. Open a forum and choose a topic
2. Look at the number of replies listed for that topic
3. Open the topic and count the number of posts
4. Num posts = stated number of replies, but the first post should not be considered a reply.

**Comment by alexwebsites** [comment]
This is off in all topics. Double checked with web version and it’s off by one. A new topic should have zero replies but it’s counting as 1 reply.

**Comment by rikkitissier** [comment]
Where do you see the incorrect counts?

**Comment by alexwebsites** [comment]
All Topics page

Look at this topic with no replies, the app says it has 1 reply

https://invisioncommunity.com/forums/topic/454448-php-74/

**Comment by alexwebsites** [comment]
![6D3A9649-0EE1-4411-83B1-7C913AB7B7E0](https://user-images.githubusercontent.com/56117136/68621855-c4200c80-049e-11ea-8d9e-98ff60058e64.png)

Here’s a screen shot. To test, start a new topic and the reply count instead of zero will be 1. Like the our pick enhancement topic. There are no current replies.

**Comment by rikkitissier** [comment]
Fixed

**Comment by alexwebsites** [comment]
Still not accurate and off by 1 on my iOS app
