### ISSUE TITLE
iOS 13.1.2 font sizes overlap

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#41]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- iOS 13.1.2

## Problem

When reading posts with differing font sizes, sentences overlap.

## Steps to reproduce

1. Create a post with differing font sizes.

## Screenshot

![2824A583-FD67-4A3D-A216-C346E4941A2A](https://user-images.githubusercontent.com/55706827/66300811-e2b64500-e8ed-11e9-9c5d-f0d5c15b5068.png)

**Comment by rikkitissier** [comment]
This came up in internal testing, and unfortunately I was not able to find a solution for it. The reason is native doesn't have a way to support relative line heights like CSS does (where you can say `1.4` and then it scales). In native we have to set one line-height in pixels, so very large text ends up being bigger than that and therefore cut off.

I'll keep looking for another solution, but right now this is a known limitation.

**Comment by The-Heff** [comment]
For the purpose of reading said text in the app, could you simply display all text as the same size, regardless of how it was drafted? (e.g. font size 14 shows as size 14, font size 48 also shows as size 14...)

**Comment by rikkitissier** [comment]
That might be possible, but would it be desirable? I suppose it's arguable that it'd be more desirable than current behavior.

I'll reopen this and think on it a bit more.

**Comment by The-Heff** [comment]
I certainly think it would be. There are lots of established communities where content has been drafted with current capabilities in mind, so there's a mixture of headings in different sizes depending on the way content has been structured. Not being able to properly read the text will undoubtedly be more of a frustration and hindrance than reading it all in a single font size.

I actually noticed this on the IPS forums in a marketplace discussion thread, which is what prompted me to test it and report the bug. I was forced to read that particular support thread through a browser.

**Comment by rikkitissier** [comment]
OK I think this is going to work. 

Through testing I can see that anything up to 22px works OK. So what I've done is added a check on each node's styling; if the font-size is specified in pixels and is _bigger_ than 22, then I force it to be 22 (so it's still bigger than normal, but won't clip). If the font-size is specified in any other units (which should be quite rare), I just strip it so that it displays at normal size.

Thanks for the suggestion on this approach 👍
