### ISSUE TITLE
iOS 12.4.1 inserting an image was confusing

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#9]
## Platform

Which platform do you use?

- iOS 12.4.1

## Which feature/screen does this feedback concern?

* Image posting

## What's your feedback?

When posting an image it was not clear if I could add it inline. It appeared to be treated as an attachment and the only available interaction appeared to be to delete it.

Inline images are critical to well structured posts, at least for my community, so this would be a very important area of improvement for us.

**Comment by rikkitissier** [comment]
I definitely agree with this as an enhancement, but it's not something I want to tackle immediately - it brings additional challenges (how would moving/resizing/deleting the image work given how the app and the editor communicate, for example).

I will likely do some tests soon to try out the idea and see how it might work. If it turns out to be feasible, I'd love to get it into the editor as an enhancement later.
